from django.shortcuts import render

from logbook.views import handle_form
from logbook.models import ( 
	CNT_BIRDS_NUMBER, 		CNT_BIRDS_DIED, 		CNT_BIRDS_APPEND,
	CNT_BIRDS_REMOVED, 		CNT_BIRDS_WEIGHT, 		CNT_BIRDS_UNIF,
	CNT_CLIMAT_RTEMP, 		CNT_CLIMAT_RHUM, 		CNT_CLIMAT_CO2,
	CNT_CLIMAT_NH3, 		CNT_SERVICE_INSPECT,	CNT_SERVICE_REPAIR,
	CNT_SERVICE_SETUP,		CNT_SERVICE_REPLACE,	CNT_VET_INSPECT,
	CNT_VET_VACCINATION,	CNT_VET_CURING,
 )

def home_view(request):
	birds_workspace_items = [
			{	'title'			: 'Поголовье', 
				'id'			: CNT_BIRDS_NUMBER,
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-kiwi-bird',
				'form'			: handle_form(request, CNT_BIRDS_NUMBER),
			},
			{	'title'			: 'Падеж', 
				'id'			: CNT_BIRDS_DIED,
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-skull-crossbones',
				'form'			: handle_form(request, CNT_BIRDS_DIED),
			},	
			{	'title'			: 'Добавлено', 
				'id'			: CNT_BIRDS_APPEND,
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-plus-circle',
				'form'			: handle_form(request, CNT_BIRDS_APPEND),
			},	
			{	'title'			: 'Изьято', 
				'id'			: CNT_BIRDS_REMOVED,
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-minus-circle',
				'form'			: handle_form(request, CNT_BIRDS_REMOVED),
			},	
			{	'title'			: 'Перемещение', 
				'id'			: 'BidrsMovedModalForm', 
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-arrow-alt-circle-right',
				'form'			: None,
			},	
			{	'title'			: 'Вес', 
				'id'			: CNT_BIRDS_WEIGHT,
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-balance-scale',
				'form'			: handle_form(request, CNT_BIRDS_WEIGHT),
			},	
			{	'title'			: 'Однородность', 
				'id'			: CNT_BIRDS_UNIF,
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-feather',
				'form'			: handle_form(request, CNT_BIRDS_UNIF),
			},		
		]

	climat_workspace_items = [
			{	'title'			: 'Температура', 
				'id'			: CNT_CLIMAT_RTEMP, 
				'color_class'	: 'warning', 
				'icon_class'	: 'fas fa-thermometer-three-quarters',
				'form'			: handle_form(request, CNT_CLIMAT_RTEMP),
			},
			{	'title'			: 'Влажность', 
				'id'			: CNT_CLIMAT_RHUM,
				'color_class'	: 'warning', 
				'icon_class'	: 'fas fa-tint',
				'form'			: handle_form(request, CNT_CLIMAT_RHUM),
			},	
			{	'title'			: 'СО2', 
				'id'			: CNT_CLIMAT_CO2,
				'color_class'	: 'warning', 
				'icon_class'	: 'fab fa-cloudscale',
				'form'			: handle_form(request, CNT_CLIMAT_CO2),
			},	
			{	'title'			: 'NH3', 
				'id'			: CNT_CLIMAT_NH3,
				'color_class'	: 'warning', 
				'icon_class'	: 'fab fa-cloudscale',
				'form'			: handle_form(request, CNT_CLIMAT_NH3),
			},		
		]

	service_workspace_items = [
			{	'title'			: 'Настройка', 
				'id'			: CNT_SERVICE_SETUP, 
				'color_class'	: 'dark', 
				'icon_class'	: 'fas fa-cog',
				'form'			: handle_form(request, CNT_SERVICE_SETUP),
			},
			{	'title'			: 'Осмотр', 
				'id'			: CNT_SERVICE_INSPECT, 
				'color_class'	: 'dark', 
				'icon_class'	: 'fas fa-clipboard-check',
				'form'			: handle_form(request, CNT_SERVICE_INSPECT),
			},
			{	'title'			: 'Ремонт', 
				'id'			: CNT_SERVICE_REPAIR, 
				'color_class'	: 'dark', 
				'icon_class'	: 'fas fa-tools',
				'form'			: handle_form(request, CNT_SERVICE_REPAIR),
			},
			{	'title'			: 'Замена', 
				'id'			: CNT_SERVICE_REPLACE, 
				'color_class'	: 'dark', 
				'icon_class'	: 'fas fa-sync-alt',
				'form'			: handle_form(request, CNT_SERVICE_REPLACE),
			},
		]

	vet_workspace_items = [
			{	'title'			: 'Осмотр', 
				'id'			: CNT_VET_INSPECT,
				'color_class'	: 'primary', 
				'icon_class'	: 'fas fa-eye',
				'form'			: handle_form(request, CNT_VET_INSPECT),
			},
			{	'title'			: 'Вакцинация', 
				'id'			: CNT_VET_VACCINATION, 
				'color_class'	: 'primary', 
				'icon_class'	: 'fas fa-syringe',
				'form'			: handle_form(request, CNT_VET_VACCINATION),
			},
			{	'title'			: 'Лечение', 
				'id'			: CNT_VET_CURING,
				'color_class'	: 'primary', 
				'icon_class'	: 'fas fa-briefcase-medical',
				'form'			: handle_form(request, CNT_VET_CURING),
			},
		]

	context = {
		'room': 13,
		'birds_workspace_items': birds_workspace_items,
		'climat_workspace_items': climat_workspace_items,
		'service_workspace_items': service_workspace_items,
		'vet_workspace_items': vet_workspace_items,
	}
	return render(request, 'base/home.html', context)

