from django.shortcuts import render

from poultry_statistics.views import handle_form
from poultry_statistics.models import ( 
	CNT_BIRDS_NUMBER, CNT_BIRDS_DIED, CNT_BIRDS_APPEND,
	CNT_BIRDS_REMOVED, CNT_BIRDS_WEIGHT, CNT_BIRDS_UNIF,
	CNT_CLIMAT_RTEMP, CNT_CLIMAT_RHUM, CNT_CLIMAT_CO2,
	CNT_CLIMAT_NH3 )


def home_view(request):
	birds_workspace_items = [
			{	'title'			: 'Поголовье', 
				'id'			: 'BirdsNumberModalForm', 
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-kiwi-bird',
				'form'			: handle_form(request, CNT_BIRDS_NUMBER),
			},
			{	'title'			: 'Падеж', 
				'id'			: 'BirdsDeadModalForm', 
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-skull-crossbones',
				'form'			: handle_form(request, CNT_BIRDS_DIED),
			},	
			{	'title'			: 'Добавлено', 
				'id'			: 'BirdsAddedModalForm', 
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-plus-circle',
				'form'			: handle_form(request, CNT_BIRDS_APPEND),
			},	
			{	'title'			: 'Изьято', 
				'id'			: 'BirdsRemovedModalForm', 
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-minus-circle',
				'form'			: handle_form(request, CNT_BIRDS_REMOVED),
			},	
			{	'title'			: 'Перемещение', 
				'id'			: 'BidrsMovedModalForm', 
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-arrow-alt-circle-right',
				'form'			: None,
			},	
			{	'title'			: 'Вес', 
				'id'			: 'BidrsWeightModalForm', 
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-balance-scale',
				'form'			: handle_form(request, CNT_BIRDS_WEIGHT),
			},	
			{	'title'			: 'Однородность', 
				'id'			: 'BidrsUnifModalForm', 
				'color_class'	: 'success', 
				'icon_class'	: 'fas fa-feather',
				'form'			: handle_form(request, CNT_BIRDS_UNIF),
			},		
		]

	climat_workspace_items = [
			{	'title'			: 'Температура', 
				'id'			: 'TempModalForm', 
				'color_class'	: 'warning', 
				'icon_class'	: 'fas fa-thermometer-three-quarters',
				'form'			: handle_form(request, CNT_CLIMAT_RTEMP),
			},
			{	'title'			: 'Влажность', 
				'id'			: 'HumidityModalForm', 
				'color_class'	: 'warning', 
				'icon_class'	: 'fas fa-tint',
				'form'			: handle_form(request, CNT_CLIMAT_RHUM),
			},	
			{	'title'			: 'СО2', 
				'id'			: 'CO2ModalForm', 
				'color_class'	: 'warning', 
				'icon_class'	: 'fab fa-cloudscale',
				'form'			: handle_form(request, CNT_CLIMAT_CO2),
			},	
			{	'title'			: 'NH3', 
				'id'			: 'NH3ModalForm', 
				'color_class'	: 'warning', 
				'icon_class'	: 'fab fa-cloudscale',
				'form'			: handle_form(request, CNT_CLIMAT_NH3),
			},		
		]

	service_workspace_items = [
			{	'title'			: 'Настройка', 
				'id'			: 'ServiceSetupModalForm', 
				'color_class'	: 'dark', 
				'icon_class'	: 'fas fa-cog',
				'form'			: None,
			},
			{	'title'			: 'Осмотр', 
				'id'			: 'ServiceLookupModalForm', 
				'color_class'	: 'dark', 
				'icon_class'	: 'fas fa-clipboard-check',
				'form'			: None,
			},
			{	'title'			: 'Ремонт', 
				'id'			: 'ServiceRepairModalForm', 
				'color_class'	: 'dark', 
				'icon_class'	: 'fas fa-tools',
				'form'			: None,
			},
			{	'title'			: 'Замена', 
				'id'			: 'ServiceReplaceModalForm', 
				'color_class'	: 'dark', 
				'icon_class'	: 'fas fa-sync-alt',
				'form'			: None,
			},
		]

	vet_workspace_items = [
			{	'title'			: 'Осмотр', 
				'id'			: 'VetLookupModalForm', 
				'color_class'	: 'primary', 
				'icon_class'	: 'fas fa-eye',
				'form'			: None,
			},
			{	'title'			: 'Вакцинация', 
				'id'			: 'VetVaccinationModalForm', 
				'color_class'	: 'primary', 
				'icon_class'	: 'fas fa-syringe',
				'form'			: None,
			},
			{	'title'			: 'Лечение', 
				'id'			: 'VetCuringModalForm', 
				'color_class'	: 'primary', 
				'icon_class'	: 'fas fa-briefcase-medical',
				'form'			: None,
			},
		]

	context = {
		'room': 13,
		'birds_workspace_items': birds_workspace_items,
		'climat_workspace_items': climat_workspace_items,
		'service_workspace_items': service_workspace_items,
		'vet_workspace_items': vet_workspace_items,
	}
	return render(request, 'base/home.html', context)

