# Generated by Django 3.2.12 on 2022-02-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TextRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата')),
                ('content_type', models.CharField(max_length=100, verbose_name='Тип записи')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.room', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Запись (text)',
                'verbose_name_plural': 'Записи (text)',
            },
        ),
        migrations.CreateModel(
            name='IntegerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата')),
                ('content_type', models.CharField(max_length=100, verbose_name='Тип записи')),
                ('value', models.IntegerField(verbose_name='Значение')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.room', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Запись (integer)',
                'verbose_name_plural': 'Записи (integer)',
            },
        ),
        migrations.CreateModel(
            name='FloatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата')),
                ('content_type', models.CharField(max_length=100, verbose_name='Тип записи')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.room', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Запись (float)',
                'verbose_name_plural': 'Записи (float)',
            },
        ),
    ]
