# Generated by Django 3.2.12 on 2022-02-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещения'},
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(verbose_name='Номер помещения'),
        ),
    ]
