# Generated by Django 3.2.12 on 2022-08-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_alter_textrecord_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('add_livestock_record', 'Can add a livestock category records'), ('add_climat_record', 'Can add a climat category records'), ('add_service_record', 'Can add a service category records'), ('add_vet_record', 'Can add a veterinarian category records')], 'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещения'},
        ),
    ]
